# Generated by Django 4.1.2 on 2022-10-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=25)),
                ('fiyat_eski', models.IntegerField()),
                ('fiyat_guncel', models.IntegerField()),
            ],
        ),
    ]
