# Generated by Django 4.1.2 on 2022-10-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_urunler_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler_Metal_degil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=25)),
                ('fiyat_eski', models.IntegerField()),
                ('fiyat_guncel', models.IntegerField()),
                ('resim', models.FileField(null=True, upload_to='filmler/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Urunler',
            new_name='Urunler_Metal',
        ),
    ]
